version: '3.7'

services:
  Oaapi.webapi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Port=5673
      - MONGODB_URI=mongodb://mongo:27018/oaapi_db
    ports:
      # - "7012:80"
      - "5000:80"
    networks:
      - common_networks
    depends_on:
      - rabbitmq
      - logconsumers.worker
      - mongo

  logconsumers.worker:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672
      - RabbitMQ__Ssl__Enabled=false    
      - MONGODB_URI=mongodb://mongo:27018/oaapi_db
    networks:
      - common_networks
    depends_on:
      - rabbitmq
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - common_networks

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - common_networks
    volumes:
      - mongo_data:/data/db

networks:
  common_networks:
    driver: bridge

volumes:
  mongo_data:
