#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:8.0 AS base
USER app
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["WorkerService/OA.LogService.Worker/OA.LogService.Worker.csproj", "WorkerService/OA.LogService.Worker/"]
COPY ["Infrastructure/OA.Infrastructure/OA.Infrastructure.csproj", "Infrastructure/OA.Infrastructure/"]
COPY ["Infrastructure/OA.Persistence/OA.Persistence.csproj", "Infrastructure/OA.Persistence/"]
COPY ["Core/OA.Domain/OA.Domain.csproj", "Core/OA.Domain/"]
RUN dotnet restore "./WorkerService/OA.LogService.Worker/OA.LogService.Worker.csproj"
COPY . .
WORKDIR "/src/WorkerService/OA.LogService.Worker"
RUN dotnet build "./OA.LogService.Worker.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./OA.LogService.Worker.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OA.LogService.Worker.dll"]